---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::pdf_document2:
    template: templates/template.tex
  bookdown::html_document2: default
  bookdown::word_document2: default
documentclass: book
bibliography: [bibliography/references.bib, bibliography/additional-references.bib]
---

# Literature Review
\minitoc <!-- this will include a mini table of contents-->

This chapter will review literature related to financial development, trade opennes and economic growth

## Financial Development



Finance is special as it is an input to much of economic activity. An efficient financial system is essential to facilitate economic transactions and more profitable technologies 
in production. A stable currency and an efficient payment system reduce the uncertainty and costs of economic transactions. 

The development of the financial sector is thus intimately related to the development of the whole economy. The contribution of finance to growth is best seen in terms of an efficient and adaptable payments system and in terms of saving mobilization and resource pooling! 

To sustain economic growth, the financial sector must mobilize domestic resources efficiently,
allocate them efficiently to finance new productive economic activities. By fulfilling 
these functions, financial systems can contribute to the growth and stability of the 
economy. It has therefore become increasingly important to identify and assess the potential role of an improved financial sector in the process of economic development. 

Financial development is the progress in financial sector in terms of depth, efficiency, accessibility and stability (Svirydzenka (2016)). Financial sector refers to the set of institutions, instruments, and markets for financial products. This also includes the legal and regulatory framework that permit transactions to be made through the extension of credit.

The relationship between the two phenomena of financial sector development and economic growth has already been investigated in the 1960s by Goldsmith (1969). McKinnon (1973) and Shaw (1973) pioneered theoretical analyses which led to the conclusion that the liberalization and development of the financial sector could promote economic growth. 

Since then a number of theoretical studies have tried to identify the role of financial intermediation in economic development. The theoretical literature studies how economic incentives, production opportunities, and policies in the emergence of financial services prompt individuals to make investment decisions which ultimately determine the rate of economic growth. They have identified various channels such as evaluation of projects and entrepreneurship', diversification of risk6, and liquidity risk management', which have favourable impacts on growth through increase in the resources and efficiency of productive capital, technological specification, and elimination of premature liquidation of capital'. 

A large body of evidence suggests that financial sector development plays a huge role in eco-
nomic development. The main rationale for linking financial development to economic growth is
that developed financial systems perform critical functions that enhance the efficiency of intermediation through reduction of information, transaction and monitoring costs (Levine (2004)).

Olgu, Dinçer, and Hacıoglu (2014) define financial developments as enabling infrastructure
(factors, policies, and institutions) that lead to effective financial intermediation and markets, and deep and broad access to capital and financial services. This constitutes institutional and business environments, financial intermediaries and markets that provide basic support for a financial system.

Virtually all the studies have demonstrated the existence of a positive correlation 
between financial development and the development of the economy as a whole. 

**Fortunately** there is concrete definition of financial development and the measure of 
financial sector development developed by WOrld Bank (2019).

## Trade Openness




essays on trade, growth ali raza.pdf

## Economic Growth