---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::pdf_document2:
    template: templates/template.tex
  bookdown::html_document2: default
  bookdown::word_document2: default
documentclass: book
#bibliography: [bibliography/references.bib, bibliography/additional-references.bib]
---

```{block type='savequote', quote_author='(ref:cicero-quote)', include=knitr::is_latex_output()}
Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...

There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
```
(ref:cicero-quote) --- Cicero's *de Finibus Bonorum et Malorum*.

<!-- 
Notes for adding an opening quote in PDF output:
i) add the reference for the quote with the chunk option quote_author="my author name",
ii) include=knitr::opts_knit$get('rmarkdown.pandoc.to') == 'latex' means that these quotes are only included when output is latex (in HTML output, it would appear by the end of the previous page)
iii) You can't use markdown syntax inside chunk options, so if you want to e.g. italicise a book name in the quote reference use a 'text reference': Create a named piece of text with '(ref:label-name) My text', then link to this in the chunk option with quote_author='(ref:label-name)'
-->

# Research Design and Methodology {#method}
\minitoc <!-- this will include a mini table of contents-->

## Introduction

<!-- LaTeX normally does not indent the first line after a heading - however, it does so after the mini table of contents. You can manually tell it not to with \noindent -->
\noindent There are three steps in this study. 
First: assembling all variables and available data that are suggested by theoretical models and previous studies as the determinants of financial development and economic growth.
Second: identifying the best Machine Learning technique that best find linear and non-linear
patterns in the data, i.e. predicts financial development and economic growth. Several Machine
Learning techniques will be tested using the pooled data including Artificial Neural Network,
Boosting, Bootstrap Aggregating, Random Forest predictors and Regression Tree. This is impor-
tant because, at least theoretically, there may be reason to believe that many of the correlates of
financial development and economic growth have complex non-linear impacts because strategic
complementarities between variables can lead to multiple possible growth equilibria.
The goal of this second step is to develop parsimonious cross-validated lists of predictive variables as (i) the study will use factor analysis methods to extract the variation from different, correlated variables, to identify specific classes of variables, (ii) the study will use various Machine Learning technologies to identify the most predictive among these factors and other variables, and winnow out the non-predictive variables.
Together, these address some of the over-fitting problems and help policy makers identify predictive policy levers. At the same time, to the extent that these steps do not estimate parameters, the issue of biased or inconsistent parameters does not arise freeing researchers from some of the econometric problems raised by endogeneity.

Therefore, to the extent that these techniques develop a parsimonious list of predictive vari-
ables, the techniques can offer a cross-validated sense of which theoretical models predict well, and therefore light a path toward a potential unified theory of financial development and economic growth. Moreover, they can also offer the policy maker some science by giving them a validated way to distinguish between the impacts of different variables of financial developments on economic growth.

Third: evaluating models’ performance and interpreting results. To evaluate model performance, this study will use rolling out-of-sample forecasts. The study will also assess the importance of each predictor by constructing variable importance measures for each of the Machine Learning models. Marginal Effects and Partial Dependence Plots (PDPs) will be used to visualize how, all else equal, a change in a covariate affects financial development and economic growth in the learning sample.

These graphs might illustrate how variables identified as good predictors of financial development relates (perhaps non-linearly) to economic growth. By identifying the variables that have the most predictive power we could help develop a framework to distinguish between competing theoretical explanations of growth.

Moreover, this Machine Learning approach can help eliminate correlates that do not predict
financial development and economic growth well. Presumably, correlates that do not predict well cannot really be considered as variables that cause growth. Moreover, this approach offer a better understanding of how growth can be predicted, which will be of particular help to policy makers as they design policies of economic growth.

The study will derive data from World Bank, the International Monetary Fund (IMF), Bank In-
donesia and Statistics Indonesia databases. The Global Financial Development Database of World
Bank is an extensive dataset of financial system characteristics that contains 108 indicators, capturing various aspects of financial institutions and markets (Eric (2017)). The Database includes measures of (1) depth, (2) access, (3) efficiency, and (4) stability of financial systems. Each of these characteristics is captured both for (1) financial institutions (for example banks and insurance companies), and (2) financial markets (such as stock markets and bond markets).

The study will also use IMF Financial Development Index that contains nine indices summarising financial institutions and financial markets are in terms of their depth, access, and efficiency across countries (Svirydzenka (2016)). Other related data will be compiled from Bank Indonesia, Statistics Indonesia, the Financial Services Authority (OJK) and streaming data provider. Machine learning techniques will be implemented using Python and R (R Core Team (2023)).



## Research Philosophies

### Research Definition 
### Research Philosophical Assumptions 
### Research Paradigms 
#### Positivism 
#### Interpretivism 
### Research Approach 
## Research Design 
### Data Triangulation 
## Justification of Research Methods
## Limitations of this study

- or see:

- Analysing_Financial_Distress_in_Malaysian_Islamic_Banks_Exploring_Integrative_Predictive_Methods.pdf

- Empirical Analysis of the Link between Politics and Stock return behaviour 2018LEIXLPhD.pdf

- check IV. essay two: political regime and stock market for machine learning

- Machine Learning Applications In Finance_Wei-Z-2019-PhD--Thesis.pdf

- Machine learning in stock indices trading and pairs trading 2021ZongPhD.pdf

- the influence of economic linkages on stock return.pdf



We are very aware of the limitations of Machine Learning. Foremost, predictive models are not
the same as causal models. The models in this study will not say about causation. Even though
this study cannot identify or establish causality, the results could help investigator identify potential pathways for causality through further theoretical modeling and traditional econometrics.

Machine Learning ought to be part of an iterative process toward a unified predictive theory of
financial development and economic growth. Furthermore, this step is a useful beginning of a process leading toward a unique predictive theory of financial development and economic growth in Indonesia.

## Data

The eﬀect of trade on economic growth is studied using an unbalanced panel dataset
spanning the period 1970 to 2012 (inclusively). To account for business cycle ﬂuctua-
tions, and in line with existing studies, we average 3 our dataset into non-overlapping
5 year periods - 1970-1974, 1975-1979, ... , 2010-2012 - resulting in a maximum of
795 observations across a maximum of 9 data points; the dataset covers 107 countries in 7 regions incorporating a mix of developed and developing economies. We construct growth rates using data from Feenstra et al. (2015) on Real GDP per capita (henceforth GDP Growth), measured in 2010 constant dollars, and Total Factor Productivity (henceforth TFP Growth), measured as a Torqvist Index, as our dependent variables. Appendix A contains tables describing the nature of our dataset in detail.

### Trade Openness

As mentioned, traditional measures have been questioned as to whether they appropriately capture an economy’s openness to trade (Rodriguez & Rodrik (2000)).
To address this shortcoming, and to oﬀer newer evidence, we primarily choose to
capture openness to trade by a network-based measure developed by Duernecker
et al. (2014). We also compare this to the share of exports and imports over GDP
(henceforth Trade Flows). In what follows, we summarise the construction and the
interpretation of the Duernecker et al. (2014) measure.

### Financial Development

## Methodology

This section describes the two-part estimation approach used in this chapter. The ﬁrst part involves estimating a number of parametric models in order to test and estimating PDP, contribution of variables, SHAP etc from XAI methods that allow the relevance and shape of trade and finance with respect GDP Growth.

### Parametric Models

Our parametric model is an additively-separable version of the canonical growth
regression and is speciﬁed as:

- add equation here


is an OECD dummy, In. Incomeit measures Real GDP at the beginning of every
ﬁve year period (1970, 1975,..., 2010), Investmentit measures investment in physi-
cal capital as a share of GDP, Human Capit is an index that measures schooling,
Pop. Growthit measures population growth `a la Mankiw et al. (1992), Govt. Sizeit
measures government consumption as a share of GDP, Inﬂationit measures CPI in-
ﬂation, and Tradeit measures openness to trade according to the measures in section
2.2.1; ǫit is an additive error term distributed with zero mean and constant variance,
and i refers to country while t refers to time, respectively.

In. Incomeit tests for conditional convergence in GDP across countries. Investmentit
acts as a measure of gross capital formation and Pop. Growthit proxies demographic
trends. Historical empirical research has shown these variables to have a signiﬁ-
cant eﬀect on economic growth (Levine & Renelt (1992)) and their inclusion in our
framework allows the Solow hypothesis to be tested. We also include Inﬂationit and
Govt. Sizeit to control for macroeconomic stability. As a ﬁnal variable, we include
Human Capit, based on mean years of schooling per capita and returns to schooling
for the population aged 15+. The inclusion of In. Incomeit and Human Capit as a
cubic stems from evidence that these variables aﬀect growth in a nonlinear fashion
(Kalaitzidakis et al. (2001), Mamuneas et al. (2006) and Maasoumi et al. (2007)).
The inclusion of dummies relating to time, region, and economic classiﬁcation ac-
count for idiosyncratic economic conditions across these variables.

Despite Durlauf et al. (2005) identifying over 140 potential variables in the debate
over convergence, we restrict our additional variables to these for two reasons. First, by readily including every available variable we increase the probability of colliniar-
ities and we increase the likelihood of over-ﬁtting our model. Second, and more
importantly, nonparametric techniques are exhaustive in their data requirements
and are not immune to the curse of dimensionality: as the number of variables in-
creases, the rate at which the estimates converge to their conditional means slows.
This requires that we, similar to previous nonparametric studies, adopt a parsimo-
nious approach that ensures our coeﬃcient estimates are reliable.

In terms of estimators, we perform Pooled Ordinary Least Squares (OLS), Two-Way
Fixed Eﬀects (FE), and Two-Stage Least Squares (2SLS) regressions, respectively,
of (2.1). In the case of the 2SLS regressions we include a landlocked dummy and
a measure of equatorial distance as potential instruments for Tradeit in the ﬁrst
stage, and then substitute the resulting ﬁtted values of Tradeit in the second stage
to estimate (2.1). One reason we opt for three diﬀerent parametric models is to
determine whether the eﬀect of trade on GDP Growth or TFP Growth is subject
to model choice. The other reason is to determine the suitability of our constructed
dataset by identifying whether the resulting coeﬃcients and their standard errors
are in line with the existing literature.

### Explainable Artificial Intelligence


