
Selamat datang di situs buku Analisis Ekonomi dan Keuangan dengan RStudio.

::: byline
[`Tedy Herlambang`](https://bangtedy.github.io)\
January 2024
:::

::::::

## Sinopsis {.unnumbered}

Buku ini berisi berbagai kasus analisis ekonomi dan keuangan dengan menggunakan R dan RStudio. Materi yang dibahas untuk mahasiswa S1 atau S2.

Saya berharap pembaca dapat mengambil satu gagasan dari buku ini dalam melakukan investigasi ekonomi dan keuangan secara kuantitatif: data dan alat-alat analisis tidak sempurna. Namun, ketika kita memahami kekuatan dan kelemahan alat-alat ini, kita dapat menggunakannya untuk menemukan hal-hal menarik di dalam ekonomi dan keuangan.

Jika Anda punya ide untuk perbaikan, tambahan materi atau menemukan kesalahan di buku ini silakan menghubungi saya.
Terima kasih.

## Ucapan Terima Kasih {.unnumbered}

Terima kasih yang sebesar-besarnya saya sampaikan kepada: Prof. Abdul Haris, Dr. Titik Musriati dan Dr. Ngatimun (Universitas Panca Marga), Muhammad Agus Nugroho dan Rifaldi Kadir (UIN Gorontalo), Rudi Masniadi (Universitas Teknologi Sumbawa), Erlyn Yuniashri dan Ajeng Kartika Galuh (Universitas Brawijaya Malang), Oktaviani Ika Wijayanti, Frederic Winston Nalle (Universitas Timor), Yeni Puspita (Universitas Negeri Jember) dan Muhammad Rizal (Universitas Islam Malang).

```{=tex}
\begin{flushright}
Tedy Herlambang \\
UPM \\
4 Januari 2024
\end{flushright}
```
